site_name: 1zyik's Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette: 
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black 
      accent: amber
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: amber
      accent: yellow

# Markdown Extensions
markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Footer details
extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/1zyik
    - icon: fontawesome/brands/twitter
      link: https://github.com/1zyik
    - icon: fontawesome/brands/linkedin
      link: https://github.com/1zyik

copyright: |
  &copy; 2024 <a href="https://github.com/1zyik" target="_blank" rel="noopener">Isaac Adepitan</a> 